### ISSUE TITLE
lyz plugin for LyX doesn't work

### ISSUE THREAD

**Issue by matteodellamico** [extraymond/zotero-snap#10]
Hi,

the lyz plugin (https://github.com/wshanks/lyz) to interface Zotero with LyX seems not to work--it can't open the ~/.lyx/lyxpipe file.

Is there a work-around I can use to solve this?

Thanks a lot!

**Comment by extraymond** [comment]
I'm not familiar with lyz, but can it be configured under non .hidden folders? Snaps prevent apps to access .{folder_name} folders for security reasons.

**Comment by matteodellamico** [comment]
Thanks, that works.

**Comment by extraymond** [comment]
Glad it helped, closing i now.
