### ISSUE TITLE
New patches since 6.0.3

### ISSUE THREAD

**Issue by MarieLSJ** [extraymond/zotero-snap#20]
Dear @extraymond,

Thanks for taking the time to create and maintain a Zotero snap! I'm very grateful as it's made it super easy to download it on the Ubuntu distribution I installed on my new work computer.

I have however been getting a "Software Update" popup a few times a day indicating it's unable to update. Looking at the [changelog](https://www.zotero.org/support/changelog) on the Zotero website, there's been a few patches out since March, the latest for Linux being 6.0.10 (July 18, 2022).

When you have a moment, it would be great if you could update the snap.

Enjoy the rest of the summer!

Marie

**Comment by extraymond** [comment]
@MarieLSJ Thanks! Got carried away by work a bit, will try to release ASAP.

**Comment by extraymond** [comment]
Updated! Thanks for the feedback.
