### ISSUE TITLE
Unable to update-popup - Issue with permissions

### ISSUE THREAD

**Issue by jay-sf** [extraymond/zotero-snap#24]
Hi and thanks for maintaining **zotero-snap!**

I'm using Ubuntu 22.04LTS and zotero-snap 6.0.12.

This looks very promising, but there appears to be an issue with updating, or auto-updates. I assume, updates should (or should not) work automatically. Regardless, since Sep 24 as I installed the snap, I'm constantly getting this popup: 

![](https://i.stack.imgur.com/WZPdV.png)

It also appears when clicking _Help > Check for Updates..._  It looks very unusual, usually I don't have to change permissions for snaps.

Please note that 

```
$ sudo snap refresh
All snaps up to date.
```
There is a [related post](https://forums.zotero.org/discussion/96934/how-to-update-zotero-snap-on-ubuntu-22-04/p1) in the Zotero Forum that suggests contacting you.

It would be nice if you could look into the issue.

Thanks very much.

**Comment by extraymond** [comment]
Yeah, the builtin update features is disabled because the snap is suppose to do the update for the user.
I'll try to update the snap ASAP.

**Comment by extraymond** [comment]
It's updated! You can refresh now.

**Comment by jay-sf** [comment]
Now it doesn't work anymore, it's detecting an update, 6.0.18 I guess, but I can neither update nor `snap refresh`. Can you fix this for working with any update? Thanks.

In also noticed the new filed ticket: https://github.com/extraymond/zotero-snap/issues/26

Cheers!

**Comment by extraymond** [comment]
> Now it doesn't work anymore, it's detecting an update, 6.0.18 I guess, but I can neither update nor `snap refresh`. Can you fix this for working with any update? Thanks.
> 
> In also noticed the new filed ticket: #26
> 
> Cheers!

The stable channel had 6.0.18 now, you might want to check again and see if that works.
