### ISSUE TITLE
Cannot open display

### ISSUE THREAD

**Issue by tseppelt** [extraymond/zotero-snap#25]
I just updated to version 6.0.15 2022-10-19 (46). When I call ``zotero-desktop`` I get the the following error ``Error: cannot open display: :0``. The same happens with the other versions available via snap store, i.e.
```
  latest/stable:    6.0.15 2022-10-19 (46) 79MB -
  latest/candidate: 6.0.15 2022-10-19 (48) 79MB -
  latest/beta:      beta   2022-10-19 (49) 84MB -
  latest/edge:      6.0.15 2022-10-19 (47)
```

**Comment by nekoisbest** [comment]
> I just updated to version 6.0.15 2022-10-19 (46). When I call `zotero-desktop` I get the the following error `Error: cannot open display: :0`. The same happens with the other versions available via snap store, i.e.
> 
> ```
>   latest/stable:    6.0.15 2022-10-19 (46) 79MB -
>   latest/candidate: 6.0.15 2022-10-19 (48) 79MB -
>   latest/beta:      beta   2022-10-19 (49) 84MB -
>   latest/edge:      6.0.15 2022-10-19 (47)
> ```

Same situation for me. I am running Ubuntu 22.04 LTS.
Since snap automatically updated Zotero to version 6.0.15, I can no longer launch it.

My temporary solution: just rollback to the previous version with the command `snap revert zotero-snap`.
The version is rollbacked to 6.0.12. At least it can be launched on my PC.
Hope it helps.

**Comment by MarcT0K** [comment]
Same problem here. The revert also worked as a temporary solution for me.

**Comment by extraymond** [comment]
Ah I think it's something related to WAYLAND. I'll try to update it! Thx for catching this.

**Comment by extraymond** [comment]
Can yall tried the candidate channel and if the fix works? If it works I'll promote it to stable.

**Comment by marcuse11** [comment]
Same problem with me. I also returned to 6.0.12. Hope they git it fixed!!!

**Comment by extraymond** [comment]
> Same problem with me. I also returned to 6.0.12. Hope they git it fixed!!!

Please try the candidate channel, the potential fix is pushed already. Need someone to confirm for me.

**Comment by MarcT0K** [comment]
@extraymond I tried `zotero-snap (candidate) 6.0.15` and it seems to work!

**Comment by marcuse11** [comment]
Sorry: What is the candidate channel, and what exactly I have to do?

**Comment by cserpell** [comment]
> Sorry: What is the candidate channel, and what exactly I have to do?

You can update the snap to that version using this command:

```bash
snap refresh zotero-snap --channel=latest/candidate
```

If it is not installed, change the `refresh` for `install`.

**Comment by cserpell** [comment]
> Please try the candidate channel, the potential fix is pushed already. Need someone to confirm for me.

It works for me as well.

**Comment by extraymond** [comment]
Thx pushed to stable now

Cristián Serpell ***@***.***> 於 2022年10月22日 週六 上午2:46 寫道：
