### ISSUE TITLE
Database Upgrade Error: attempt to write a readonly database

### ISSUE THREAD

**Issue by felixhelix** [extraymond/zotero-snap#3]
Zotero Version 5.0.82
I'm using a Snap package with Ubuntu.

Since the Update I cannot start Zotero, getting the following error:

Error: Error(s) encountered during statement execution: attempt to write a readonly database [QUERY: DELETE FROM itemTypeFields] [PARAMS: ] [ERROR: attempt to write a readonly database]
Zotero.DBConnection.prototype.queryAsync<@chrome://zotero/content/xpcom/db.js:664:13
From previous event:
_updateGlobalSchema@chrome://zotero/content/xpcom/schema.js:509:11

extraymond already suggested that 

"it's something to do with me changing the project folder to /home/$USER/Zotero other than the default one which links to /home/$USER/snap/zotero-snap/version/snap"

Does anyone has experienced a similar problem? Any ideas how to fix this?

Your's
Felix

**Comment by Jordy-VL** [comment]
I have exactly the same problem. 

Error: Error(s) encountered during statement execution: attempt to write a readonly database [QUERY: DELETE FROM itemTypeFields] [PARAMS: ] [ERROR: attempt to write a readonly database]
    Zotero.DBConnection.prototype.queryAsync<@chrome://zotero/content/xpcom/db.js:664:13
From previous event:
    _updateGlobalSchema@chrome://zotero/content/xpcom/schema.js:509:11

**Comment by extraymond** [comment]
Hi! Thanks for reporting.

If I understand correctly, in normal setup, there's no such thing as zotero being installed on different version path, which snaps do. So here's my suggestion, upon app firstl launch to assign app folder from either :
1. the default one to a fixed path outside of ~/snap/zotero-snap/version/
2. to a folder designed to be shared by all versions of the snap ~/snap/zotero-snap/common.

Can you help me trying the following?
1. rm ~/snap/zotero-snap(maybe backup the folder if you want to try to restore it later)
2. start zotero-snap again and assign the project folder to the the path suggested above. You can point to a removable media if you have enabled the slot interface.
3. It might pass the upcoming update if successfully.

Again thanks guys for reporting, looking forward to get feedback from you.

**Comment by Jordy-VL** [comment]
Hi Extraymond, 

Your solution worked. 

One caveat though for the below instructions to work succesfully: 
> DO NOT REMOVE ~/snap/zotero-snap

So in short, what I did was: 
1) mv ~/snap/zotero-snap ~/snap/zoter-snapbkup; cd ~/snap/zoter-snapbkup
2) restart zotero-snap, which recreates the ~/snap/zotero-snap
3) mv 10 ../zotero-snap/common/  #move latest version from bkup to common
4) in zotero-snap UI, go to "edit", then "preferences", "advanced", "files-and-folders" and set "data directory location", custom to **_~/snap/zotero-snap/common/10/Zotero_**

After a restart everything was working fine again. 

Thanks!

**Comment by extraymond** [comment]
> Hi Extraymond,
> 
> Your solution worked.
> 
> One caveat though for the below instructions to work succesfully:
> 
> > DO NOT REMOVE ~/snap/zotero-snap
> 
> So in short, what I did was:
> 
>     1. mv ~/snap/zotero-snap ~/snap/zoter-snapbkup; cd ~/snap/zoter-snapbkup
> 
>     2. restart zotero-snap, which recreates the ~/snap/zotero-snap
> 
>     3. mv 10 ../zotero-snap/common/  #move latest version from bkup to common
> 
>     4. in zotero-snap UI, go to "edit", then "preferences", "advanced", "files-and-folders" and set "data directory location", custom to **_~/snap/zotero-snap/common/10/Zotero_**
> 
> 
> After a restart everything was working fine again.
> 
> Thanks!

Glad to know it helped.
I think you don't need it under common/$VERSION, just common/Zotero would be fine.

If will try to update again and see if automatic refresh worked with folder setup to a custom path.

**Comment by felixhelix** [comment]
Thanks to you both - worked for me too :-)
Just wonder  Extraymond what you mean by 
'I think you don't need it under common/$VERSION, just common/Zotero would be fine.'
I first tried to set the data directory location to '~/snap/zotero-snap/common', but then zotero created a new database?
Your's
Felix

**Comment by extraymond** [comment]
Glad that helped!

For a user, after launching the snap's, it's directory structure should have list of  ~/snap/$SNAP_NAME/$VERSION folders, a current one which linked to the one you are using, and a common folder which can be seen by all versions of the snap.

I think the design is so that a snap author can decide whether there are version-specific files needed when launched, like cache or something. You can put files to other files that can be seen by all version of zotero-snap too, for example $USER/Document/Zotero.

So putting a Zotero folder under common/$VERSION would be the same as common/Zotero, and I think it would be clearer this way.

It's better to not select common as the project folder but to use common/Zotero, so that Zotero will only tried to change files in that folder. It won't do any harm, but it will make backups easier I think.

**Comment by extraymond** [comment]
Updated the landing page to notify setting another project folder.
Close this for now, thanks for anyone helping.
