### ISSUE TITLE
Zotero can't update

### ISSUE THREAD

**Issue by barrel0luck** [extraymond/zotero-snap#4]
I'm using the Zotero snap package 5.0.81
This version keeps showing up a dialog box that says:
![image](https://user-images.githubusercontent.com/44344748/77685610-980bb080-6f93-11ea-8ada-c948a7d0401b.png)
This can also be triggered by clicking Help > Check for updates
![image](https://user-images.githubusercontent.com/44344748/77685664-ad80da80-6f93-11ea-8de7-aad91a88efd0.png)

**Comment by extraymond** [comment]
@barrel0luck Thanks for reporting, snap uses different approach to handle upgrading mechanism.
So if you have received a update notification, it's because I didn't update the build script fast enough, otherwise the snap should upgrade on it's own.

Thanks for reporting!

**Comment by barrel0luck** [comment]
Can that dialog be repressed in the snap version then? That'll make it less intrusive and give you sufficient time to roll out updates. It's not like I'm dying for Zotero updates. It already functions pretty well, if you get what I mean. It's just that the dialog can get a bit irritating the way it keeps opening every now and then...
