### ISSUE TITLE
platform specific update

### ISSUE THREAD

**Issue by extraymond** [extraymond/zotero-snap#49]
## info

it seems there's a issue solely relying on tags to trigger release.
as of 6.0.37, where the release is legit as a release tag on the zotero github repo, but the release was only build for mac, so when building the snap it failed because we rely on a prebuilt deb to build the snap.
a similar issue happened with 6.0.36 which is windows exclusive.

we might need a better way to check the release and if it's worth skipping non-linux releases.

**Comment by franklegolasyoung** [comment]
Hi @extraymond, i just create a PR for update the version checking logic from Git tags to download url link. I also downgrade the version to 6.0.30 so after merging, it should auto update the correct version. Thanks.

**Comment by franklegolasyoung** [comment]
Hi @extraymond , sry this is my first time doing contribution, and I'm not very familiar with the git process. The previous PR was confusing bc the command syntax changed a little, so I've submitted a new PR with the previous changes and changed the deprecated command. Pls review it, thanks! Btw, lately I've been using zotero-snap on a daily basis, so I'm a little more sensitive to version updates, as zotero automatically detects updates and top up the update window. I can help confirm the automatic pr request if it's convenient for u.
