### ISSUE TITLE
Zotero Snap out of date

### ISSUE THREAD

**Issue by jonpolak** [extraymond/zotero-snap#5]
Thank you so much for making the zotero snap for the rest of the community. The app is saying it wants to be updated, but we need the snap to update it.... do you need help to maintain this snap uptodate?

**Comment by extraymond** [comment]
Sorry for the delay, I've been a bit sick for some time, should be staying up to state now.
Generally I would be working on making this snap under the snapcrafters organization or zotero so anyone can contribute.
Thanks for notifying, should be up to date now.

**Comment by juhalindfors** [comment]
A quick ping -- the current snap is version 5.0.92, there was a new 5.0.93 release this November. The warning about inability to update is present again at least with a new install from two days ago.
