### ISSUE TITLE
Stuck in Dark mode 

### ISSUE THREAD

**Issue by K4mpfie** [extraymond/zotero-snap#53]
Hi, for some reason, Zotero through the Snap store is only available in dark mode...

The advanced settings for it  _widget.chrome.allow-gtk-dark-theme_ and _widget.content.allow-gtk-dark-theme_ are set to _false_ (changing them does nothing)
My system theme is set to light mode
and the often online described chrome.css doesn't seem to exist 

Other things I tried so far is the Version of Zetero that is distributed by Zotero. This one does run in light theme 
I also tried to run the Version available on the Fedora Store as a flatpak, this one is stuck in dark mode aswell...
Lastly, I tried to run an extension that would provide a dark mode, this resulted in having  two different dark modes but not light mode.

I'm currently running Fedora 40 with Gnome

I also included the [Debug Output](https://paste.ubuntu.com/p/88qHfcwVQy/) available in Zotero

I'm sorry if I'm missing something really obvious, I'm pretty new to Linux, hope you can help me 
-K4

**Comment by extraymond** [comment]
Sorry for the late response, have you tried the 7.0 version and see if that works?

**Comment by K4mpfie** [comment]
Hi, all good! 
I just loaded Zotero from the candidate channel (V. 7.0.2) and was successfully able to turn on light mode and have it stay on, on relaunch! I think I can consider this fixed :D 
Looking forward to your official release. 
Thanks for the help! 
-K4

**Comment by extraymond** [comment]
Awesome!
