### ISSUE TITLE
When will 7.0.x be the latest stable version?

### ISSUE THREAD

**Issue by george-gca** [extraymond/zotero-snap#57]
When will 7.0.x be the latest stable version @extraymond? Currently the [latest stable is 6.0.35](https://snapcraft.io/zotero-snap).

**Comment by extraymond** [comment]
Hi! Currently it's in beta branch.
I intend to let it stay for at most 2 weeks and see if most stuff works as expected.

I'll try to create and migrate the last 6.0 version to a dedicated channel to let people use the old one if it also makes sense.
