### ISSUE TITLE
LibreOffice integration with Snap package

### ISSUE THREAD

**Issue by ReinerBanken** [extraymond/zotero-snap#6]
How can I install the LibreOffice plugin from the Snap package?  The issue has been raised on the Zotero group: https://forums.zotero.org/discussion/82622/cant-install-libreoffice-plugin-from-snap-package

The user scienceshaina said she figured out how to do it, but she does not provide details.

**Comment by extraymond** [comment]
@ReinerBanken  Thanks for reporting, you can do it by the following steps. The step below should get it working, step two is required if you want to install the zotero plugin for libreoffice_snap.

1. Select manual install of the word processor addon  from the zotero preference settings.
2. Copy the specified "Zotero_OpenOffice_Integration.oxt" file from the instructed path to a snap visible folder, such as ~/Downloads.
3. Open libreoffice -> addon -> install from file -> select the file you need, and it should be working.

Hope you find this usable.

**Comment by Malsasa** [comment]
I can confirm @extraymond's workaround above works on Ubuntu 20.04 with zotero-snap. Thank you very much @extraymond for making Zotero available on Snapcraft.
