### ISSUE TITLE
Problems with the PDF viewer

### ISSUE THREAD

**Issue by alinafdima** [extraymond/zotero-snap#7]
Hi,

I recently installed Zotero through snap on Ubuntu 20.04 and I use as PDF viewer FoxitReader 2.4.4.0911. Whenever I would open a PDF through Zotero, FoxitReader would not take any keyboard input and only the mouse worked, which made it almost unusable since I couldn't make comments or use any keyboard shortcuts. Furthermore, the process itself appeared to be a Zotero process which made navigation a bit more painful. After removing the snap package and installing the non-snap version, all of these issues disappeared.

**Comment by extraymond** [comment]
Thanks for notifying! Can you elaborate more the following line? Would be nice to explain what you expect to see and what happened so I can get a fair comparison.
> Furthermore, the process itself appeared to be a Zotero process which made navigation a bit more painful.

**Comment by alinafdima** [comment]
So basically in the dock it appears that I have multiple Zotero processes open, but no FoxitReader (unless opened outside of Zotero). I am pretty sure I have also tried a killall Zotero and it also killed the pdf viewer, but I have uninstalled zotero-snap and I can't verify. But I was definitely able to successfully close the main Zotero window by pressing the exit button without closing the pdf viewer. Furthermore, copy-pasting also didn't work (certainly not through keyboard shortcuts), but neither worked the middle click paste which doesn't involve the keyboard.

**Comment by extraymond** [comment]
@alinafdima Sorry for the late response,  are you still facing the same error with the latest version? I haven't receive related report from other users. 

If the problem still persist, would you mind checking the log and see if there's anything suspicious. Please try this with the zotero snap opened.

```bash
journalctl -ef -g zotero
```
